# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gnosis_v0.50.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gnosis(object):
    def setupUi(self, Gnosis):
        Gnosis.setObjectName("Gnosis")
        Gnosis.resize(682, 608)
        Gnosis.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(Gnosis)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.globalwidget = QtWidgets.QTabWidget(Gnosis)
        self.globalwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.globalwidget.setToolTip("")
        self.globalwidget.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.globalwidget.setObjectName("globalwidget")
        self.tab_SQL = QtWidgets.QWidget()
        self.tab_SQL.setObjectName("tab_SQL")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_SQL)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SQLquery = QtWidgets.QPlainTextEdit(self.tab_SQL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLquery.sizePolicy().hasHeightForWidth())
        self.SQLquery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.SQLquery.setFont(font)
        self.SQLquery.setObjectName("SQLquery")
        self.verticalLayout_4.addWidget(self.SQLquery)
        self.SQLresponse = QtWidgets.QPlainTextEdit(self.tab_SQL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLresponse.sizePolicy().hasHeightForWidth())
        self.SQLresponse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.SQLresponse.setFont(font)
        self.SQLresponse.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.SQLresponse.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SQLresponse.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.SQLresponse.setPlainText("")
        self.SQLresponse.setObjectName("SQLresponse")
        self.verticalLayout_4.addWidget(self.SQLresponse)
        self.widget_SQL_options = QtWidgets.QWidget(self.tab_SQL)
        self.widget_SQL_options.setObjectName("widget_SQL_options")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_SQL_options)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_exportConfig = QtWidgets.QWidget(self.widget_SQL_options)
        self.widget_exportConfig.setObjectName("widget_exportConfig")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_exportConfig)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_exportconfig = QtWidgets.QPushButton(self.widget_exportConfig)
        self.pushButton_exportconfig.setObjectName("pushButton_exportconfig")
        self.horizontalLayout_4.addWidget(self.pushButton_exportconfig)
        self.horizontalLayout_5.addWidget(self.widget_exportConfig, 0, QtCore.Qt.AlignBottom)
        self.widget_executeSql = QtWidgets.QWidget(self.widget_SQL_options)
        self.widget_executeSql.setObjectName("widget_executeSql")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_executeSql)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_radio_executeSql = QtWidgets.QWidget(self.widget_executeSql)
        self.widget_radio_executeSql.setObjectName("widget_radio_executeSql")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_radio_executeSql)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_pretty = QtWidgets.QRadioButton(self.widget_radio_executeSql)
        self.radioButton_pretty.setObjectName("radioButton_pretty")
        self.horizontalLayout_3.addWidget(self.radioButton_pretty, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_csv = QtWidgets.QRadioButton(self.widget_radio_executeSql)
        self.radioButton_csv.setObjectName("radioButton_csv")
        self.horizontalLayout_3.addWidget(self.radioButton_csv, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_radio_executeSql)
        self.pushButton_sql_execute = QtWidgets.QPushButton(self.widget_executeSql)
        self.pushButton_sql_execute.setObjectName("pushButton_sql_execute")
        self.verticalLayout_5.addWidget(self.pushButton_sql_execute)
        self.horizontalLayout_5.addWidget(self.widget_executeSql)
        self.widget_6 = QtWidgets.QWidget(self.widget_SQL_options)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_5.addWidget(self.widget_6, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.widget_SQL_options)
        self.globalwidget.addTab(self.tab_SQL, "")
        self.tab_cli = QtWidgets.QWidget()
        self.tab_cli.setObjectName("tab_cli")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_cli)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolBox = QtWidgets.QToolBox(self.tab_cli)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 640, 465))
        self.page.setObjectName("page")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.widget_30 = QtWidgets.QWidget(self.page)
        self.widget_30.setMaximumSize(QtCore.QSize(600, 169865))
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_42 = QtWidgets.QWidget(self.widget_30)
        self.widget_42.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_42.setObjectName("widget_42")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_42)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.UCMPub_Label = QtWidgets.QLabel(self.widget_42)
        self.UCMPub_Label.setObjectName("UCMPub_Label")
        self.horizontalLayout_25.addWidget(self.UCMPub_Label)
        self.UCMPub_IP_CLI_line = QtWidgets.QLineEdit(self.widget_42)
        self.UCMPub_IP_CLI_line.setMinimumSize(QtCore.QSize(0, 17))
        self.UCMPub_IP_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_IP_CLI_line.setObjectName("UCMPub_IP_CLI_line")
        self.horizontalLayout_25.addWidget(self.UCMPub_IP_CLI_line)
        self.verticalLayout_10.addWidget(self.widget_42)
        self.widget_43 = QtWidgets.QWidget(self.widget_30)
        self.widget_43.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_43.setObjectName("widget_43")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_43)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.UCMPubCLI_username_label = QtWidgets.QLabel(self.widget_43)
        self.UCMPubCLI_username_label.setObjectName("UCMPubCLI_username_label")
        self.horizontalLayout_26.addWidget(self.UCMPubCLI_username_label)
        self.UCMPub_Username_CLI_line = QtWidgets.QLineEdit(self.widget_43)
        self.UCMPub_Username_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Username_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Username_CLI_line.setObjectName("UCMPub_Username_CLI_line")
        self.horizontalLayout_26.addWidget(self.UCMPub_Username_CLI_line)
        self.verticalLayout_10.addWidget(self.widget_43)
        self.widget_44 = QtWidgets.QWidget(self.widget_30)
        self.widget_44.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_44.setObjectName("widget_44")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_44)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_22 = QtWidgets.QLabel(self.widget_44)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_27.addWidget(self.label_22)
        self.UCMPub_Password_CLI_line = QtWidgets.QLineEdit(self.widget_44)
        self.UCMPub_Password_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Password_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Password_CLI_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UCMPub_Password_CLI_line.setObjectName("UCMPub_Password_CLI_line")
        self.horizontalLayout_27.addWidget(self.UCMPub_Password_CLI_line)
        self.verticalLayout_10.addWidget(self.widget_44)
        self.widget_45 = QtWidgets.QWidget(self.widget_30)
        self.widget_45.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_45.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_45.setObjectName("widget_45")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_45)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_discover_nodes_UCM = QtWidgets.QPushButton(self.widget_45)
        self.pushButton_discover_nodes_UCM.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_discover_nodes_UCM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_discover_nodes_UCM.setObjectName("pushButton_discover_nodes_UCM")
        self.horizontalLayout_13.addWidget(self.pushButton_discover_nodes_UCM)
        self.verticalLayout_10.addWidget(self.widget_45)
        self.widget_46 = QtWidgets.QWidget(self.widget_30)
        self.widget_46.setObjectName("widget_46")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_46)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tableWidget_ucm_cluster_cli = QtWidgets.QTableWidget(self.widget_46)
        self.tableWidget_ucm_cluster_cli.setAlternatingRowColors(True)
        self.tableWidget_ucm_cluster_cli.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ucm_cluster_cli.setShowGrid(False)
        self.tableWidget_ucm_cluster_cli.setColumnCount(6)
        self.tableWidget_ucm_cluster_cli.setObjectName("tableWidget_ucm_cluster_cli")
        self.tableWidget_ucm_cluster_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(5, item)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_17.addWidget(self.tableWidget_ucm_cluster_cli)
        self.verticalLayout_10.addWidget(self.widget_46)
        self.widget_11 = QtWidgets.QWidget(self.widget_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_Spark_to = QtWidgets.QLabel(self.widget_12)
        self.label_Spark_to.setObjectName("label_Spark_to")
        self.horizontalLayout_14.addWidget(self.label_Spark_to)
        self.lineEdit_spark_to_address = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_spark_to_address.setObjectName("lineEdit_spark_to_address")
        self.horizontalLayout_14.addWidget(self.lineEdit_spark_to_address)
        self.verticalLayout_11.addWidget(self.widget_12, 0, QtCore.Qt.AlignTop)
        self.widget_13 = QtWidgets.QWidget(self.widget_11)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_spark_send = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_spark_send.setObjectName("pushButton_spark_send")
        self.horizontalLayout_28.addWidget(self.pushButton_spark_send)
        self.verticalLayout_11.addWidget(self.widget_13)
        self.verticalLayout_10.addWidget(self.widget_11)
        self.horizontalLayout_30.addWidget(self.widget_30)
        self.widget_47 = QtWidgets.QWidget(self.page)
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_47)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_49 = QtWidgets.QWidget(self.widget_47)
        self.widget_49.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_49.setObjectName("widget_49")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_49)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.treeWidget_ucm_cli = QtWidgets.QTreeWidget(self.widget_49)
        self.treeWidget_ucm_cli.setToolTip("")
        self.treeWidget_ucm_cli.setStatusTip("")
        self.treeWidget_ucm_cli.setObjectName("treeWidget_ucm_cli")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_ucm_cli)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_ucm_cli)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_ucm_cli)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_20.addWidget(self.treeWidget_ucm_cli)
        self.verticalLayout_12.addWidget(self.widget_49)
        self.widget_50 = QtWidgets.QWidget(self.widget_47)
        self.widget_50.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_50.setObjectName("widget_50")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_50)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_execute_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_execute_cli_ucm.sizePolicy().hasHeightForWidth())
        self.pushButton_execute_cli_ucm.setSizePolicy(sizePolicy)
        self.pushButton_execute_cli_ucm.setObjectName("pushButton_execute_cli_ucm")
        self.verticalLayout_14.addWidget(self.pushButton_execute_cli_ucm)
        self.pushButton_stop_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        self.pushButton_stop_cli_ucm.setObjectName("pushButton_stop_cli_ucm")
        self.verticalLayout_14.addWidget(self.pushButton_stop_cli_ucm)
        self.verticalLayout_12.addWidget(self.widget_50)
        self.horizontalLayout_30.addWidget(self.widget_47)
        self.toolBox.addItem(self.page, "")
        self.page_SparkIt = QtWidgets.QWidget()
        self.page_SparkIt.setGeometry(QtCore.QRect(0, 0, 640, 465))
        self.page_SparkIt.setObjectName("page_SparkIt")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_SparkIt)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_31 = QtWidgets.QWidget(self.page_SparkIt)
        self.widget_31.setMaximumSize(QtCore.QSize(600, 169865))
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_48 = QtWidgets.QWidget(self.widget_31)
        self.widget_48.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_48.setObjectName("widget_48")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_48)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.Spark_username_Label = QtWidgets.QLabel(self.widget_48)
        self.Spark_username_Label.setObjectName("Spark_username_Label")
        self.horizontalLayout_29.addWidget(self.Spark_username_Label)
        self.LineEdit_Spark_username = QtWidgets.QLineEdit(self.widget_48)
        self.LineEdit_Spark_username.setMinimumSize(QtCore.QSize(0, 17))
        self.LineEdit_Spark_username.setMaximumSize(QtCore.QSize(125, 16777215))
        self.LineEdit_Spark_username.setObjectName("LineEdit_Spark_username")
        self.horizontalLayout_29.addWidget(self.LineEdit_Spark_username)
        self.verticalLayout_2.addWidget(self.widget_48)
        self.widget_52 = QtWidgets.QWidget(self.widget_31)
        self.widget_52.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_52.setObjectName("widget_52")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_52)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_Spark_password = QtWidgets.QLabel(self.widget_52)
        self.label_Spark_password.setObjectName("label_Spark_password")
        self.horizontalLayout_32.addWidget(self.label_Spark_password, 0, QtCore.Qt.AlignLeft)
        self.LineEdit_Spark_password = QtWidgets.QLineEdit(self.widget_52)
        self.LineEdit_Spark_password.setMinimumSize(QtCore.QSize(117, 17))
        self.LineEdit_Spark_password.setMaximumSize(QtCore.QSize(125, 16777215))
        self.LineEdit_Spark_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LineEdit_Spark_password.setObjectName("LineEdit_Spark_password")
        self.horizontalLayout_32.addWidget(self.LineEdit_Spark_password)
        self.verticalLayout_2.addWidget(self.widget_52)
        self.widget_51 = QtWidgets.QWidget(self.widget_31)
        self.widget_51.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_51.setObjectName("widget_51")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_51)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_recipient_spark_address = QtWidgets.QLabel(self.widget_51)
        self.label_recipient_spark_address.setObjectName("label_recipient_spark_address")
        self.horizontalLayout_31.addWidget(self.label_recipient_spark_address)
        self.lineEdit_RecipientSparkAddress = QtWidgets.QLineEdit(self.widget_51)
        self.lineEdit_RecipientSparkAddress.setMinimumSize(QtCore.QSize(117, 17))
        self.lineEdit_RecipientSparkAddress.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lineEdit_RecipientSparkAddress.setObjectName("lineEdit_RecipientSparkAddress")
        self.horizontalLayout_31.addWidget(self.lineEdit_RecipientSparkAddress)
        self.verticalLayout_2.addWidget(self.widget_51)
        self.widget_53 = QtWidgets.QWidget(self.widget_31)
        self.widget_53.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_53.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_53.setObjectName("widget_53")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_53)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_send_output_to_Spark = QtWidgets.QPushButton(self.widget_53)
        self.pushButton_send_output_to_Spark.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_send_output_to_Spark.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_send_output_to_Spark.setObjectName("pushButton_send_output_to_Spark")
        self.horizontalLayout_15.addWidget(self.pushButton_send_output_to_Spark)
        self.verticalLayout_2.addWidget(self.widget_53)
        self.horizontalLayout.addWidget(self.widget_31, 0, QtCore.Qt.AlignLeft)
        self.widget_32 = QtWidgets.QWidget(self.page_SparkIt)
        self.widget_32.setMaximumSize(QtCore.QSize(600, 169865))
        self.widget_32.setStyleSheet("background-image: url(:/spark/512x512 spark logo.png);")
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.widget_32)
        self.toolBox.addItem(self.page_SparkIt, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 696, 414))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout_12.addWidget(self.toolBox)
        self.globalwidget.addTab(self.tab_cli, "")
        self.horizontalLayout_9.addWidget(self.globalwidget)

        self.retranslateUi(Gnosis)
        self.globalwidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gnosis)

    def retranslateUi(self, Gnosis):
        _translate = QtCore.QCoreApplication.translate
        Gnosis.setWindowTitle(_translate("Gnosis", "Gnosis"))
        self.SQLquery.setPlainText(_translate("Gnosis", "select name, description from device where name like \'SEP%\'"))
        self.pushButton_exportconfig.setText(_translate("Gnosis", "Save"))
        self.radioButton_pretty.setText(_translate("Gnosis", "Pretty"))
        self.radioButton_csv.setText(_translate("Gnosis", "CSV"))
        self.pushButton_sql_execute.setText(_translate("Gnosis", "Execute Query"))
        self.pushButton_6.setText(_translate("Gnosis", "Exit"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_SQL), _translate("Gnosis", "SQL"))
        self.UCMPub_Label.setText(_translate("Gnosis", "PUB IP"))
        self.UCMPubCLI_username_label.setText(_translate("Gnosis", "Username"))
        self.label_22.setText(_translate("Gnosis", "Password"))
        self.pushButton_discover_nodes_UCM.setText(_translate("Gnosis", "Discover Cluster"))
        self.tableWidget_ucm_cluster_cli.setSortingEnabled(True)
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(0)
        item.setText(_translate("Gnosis", "address"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(1)
        item.setText(_translate("Gnosis", "role"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(2)
        item.setText(_translate("Gnosis", "type"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(3)
        item.setText(_translate("Gnosis", "dbRole"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(4)
        item.setText(_translate("Gnosis", "hostname"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(5)
        item.setText(_translate("Gnosis", "status"))
        self.label_Spark_to.setText(_translate("Gnosis", "Spark it to: "))
        self.pushButton_spark_send.setText(_translate("Gnosis", "Send"))
        self.treeWidget_ucm_cli.headerItem().setText(0, _translate("Gnosis", "CLI Commands"))
        __sortingEnabled = self.treeWidget_ucm_cli.isSortingEnabled()
        self.treeWidget_ucm_cli.setSortingEnabled(False)
        self.treeWidget_ucm_cli.topLevelItem(0).setText(0, _translate("Gnosis", "UCM_Publisher"))
        self.treeWidget_ucm_cli.topLevelItem(0).child(0).setText(0, _translate("Gnosis", "cli_command"))
        self.treeWidget_ucm_cli.topLevelItem(1).setText(0, _translate("Gnosis", "UCM_All_Nodes"))
        self.treeWidget_ucm_cli.topLevelItem(1).child(0).setText(0, _translate("Gnosis", "cli_command_UCM_All_Nodes1"))
        self.treeWidget_ucm_cli.topLevelItem(1).child(1).setText(0, _translate("Gnosis", "cli_command_UCM_All_Nodes2"))
        self.treeWidget_ucm_cli.topLevelItem(1).child(2).setText(0, _translate("Gnosis", "cli_command_UCM_All_Nodes3"))
        self.treeWidget_ucm_cli.topLevelItem(2).setText(0, _translate("Gnosis", "IMP_All_Nodes"))
        self.treeWidget_ucm_cli.topLevelItem(2).child(0).setText(0, _translate("Gnosis", "imp_all_nodes_command_1"))
        self.treeWidget_ucm_cli.topLevelItem(2).child(1).setText(0, _translate("Gnosis", "imp_all_nodes_command_2"))
        self.treeWidget_ucm_cli.topLevelItem(2).child(2).setText(0, _translate("Gnosis", "imp_all_nodes_command_3"))
        self.treeWidget_ucm_cli.setSortingEnabled(__sortingEnabled)
        self.pushButton_execute_cli_ucm.setText(_translate("Gnosis", "START"))
        self.pushButton_stop_cli_ucm.setText(_translate("Gnosis", "STOP"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Gnosis", "UCM + IMP"))
        self.Spark_username_Label.setText(_translate("Gnosis", "Spark username"))
        self.label_Spark_password.setText(_translate("Gnosis", "Spark Password"))
        self.label_recipient_spark_address.setText(_translate("Gnosis", "Recipient Spark address"))
        self.pushButton_send_output_to_Spark.setText(_translate("Gnosis", "Send"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_SparkIt), _translate("Gnosis", "CUBE"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Gnosis", "CER"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_cli), _translate("Gnosis", "Platform"))

import spark_logo_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gnosis = QtWidgets.QDialog()
    ui = Ui_Gnosis()
    ui.setupUi(Gnosis)
    Gnosis.show()
    sys.exit(app.exec_())

