# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gnosis_v0.66.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gnosis(object):
    def setupUi(self, Gnosis):
        Gnosis.setObjectName("Gnosis")
        Gnosis.resize(1082, 809)
        Gnosis.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Gnosis)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.globalwidget = QtWidgets.QTabWidget(Gnosis)
        self.globalwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.globalwidget.setToolTip("")
        self.globalwidget.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.globalwidget.setObjectName("globalwidget")
        self.tab_SQL = QtWidgets.QWidget()
        self.tab_SQL.setObjectName("tab_SQL")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_SQL)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.tab_SQL)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(275, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ip_address_sql = QtWidgets.QLabel(self.widget_3)
        self.label_ip_address_sql.setObjectName("label_ip_address_sql")
        self.verticalLayout.addWidget(self.label_ip_address_sql)
        self.label_username_sql = QtWidgets.QLabel(self.widget_3)
        self.label_username_sql.setMinimumSize(QtCore.QSize(0, 0))
        self.label_username_sql.setObjectName("label_username_sql")
        self.verticalLayout.addWidget(self.label_username_sql)
        self.label_password_sql = QtWidgets.QLabel(self.widget_3)
        self.label_password_sql.setObjectName("label_password_sql")
        self.verticalLayout.addWidget(self.label_password_sql)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_ipaddress_sql = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_ipaddress_sql.setObjectName("lineEdit_ipaddress_sql")
        self.verticalLayout_2.addWidget(self.lineEdit_ipaddress_sql)
        self.lineEdit_username_sql = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_username_sql.setObjectName("lineEdit_username_sql")
        self.verticalLayout_2.addWidget(self.lineEdit_username_sql)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.tab_SQL)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SQLquery = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLquery.sizePolicy().hasHeightForWidth())
        self.SQLquery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.SQLquery.setFont(font)
        self.SQLquery.setObjectName("SQLquery")
        self.horizontalLayout_4.addWidget(self.SQLquery)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_6)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SQLresponse = QtWidgets.QPlainTextEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLresponse.sizePolicy().hasHeightForWidth())
        self.SQLresponse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.SQLresponse.setFont(font)
        self.SQLresponse.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.SQLresponse.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SQLresponse.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.SQLresponse.setPlainText("")
        self.SQLresponse.setObjectName("SQLresponse")
        self.horizontalLayout_3.addWidget(self.SQLresponse)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_executeSql = QtWidgets.QWidget(self.tab_SQL)
        self.widget_executeSql.setObjectName("widget_executeSql")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_executeSql)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_sql_execute = QtWidgets.QPushButton(self.widget_executeSql)
        self.pushButton_sql_execute.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_sql_execute.setMaximumSize(QtCore.QSize(141, 16777215))
        self.pushButton_sql_execute.setObjectName("pushButton_sql_execute")
        self.horizontalLayout_6.addWidget(self.pushButton_sql_execute)
        self.verticalLayout_4.addWidget(self.widget_executeSql)
        self.globalwidget.addTab(self.tab_SQL, "")
        self.tab_cli = QtWidgets.QWidget()
        self.tab_cli.setObjectName("tab_cli")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_cli)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolBox = QtWidgets.QToolBox(self.tab_cli)
        self.toolBox.setObjectName("toolBox")
        self.page_VOS = QtWidgets.QWidget()
        self.page_VOS.setGeometry(QtCore.QRect(0, 0, 1040, 720))
        self.page_VOS.setObjectName("page_VOS")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.page_VOS)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.widget_30 = QtWidgets.QWidget(self.page_VOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_30.sizePolicy().hasHeightForWidth())
        self.widget_30.setSizePolicy(sizePolicy)
        self.widget_30.setMinimumSize(QtCore.QSize(630, 0))
        self.widget_30.setMaximumSize(QtCore.QSize(600, 169865))
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_25 = QtWidgets.QWidget(self.widget_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_24 = QtWidgets.QWidget(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_15 = QtWidgets.QWidget(self.widget_24)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.UCMPub_Label = QtWidgets.QLabel(self.widget_15)
        self.UCMPub_Label.setObjectName("UCMPub_Label")
        self.verticalLayout_18.addWidget(self.UCMPub_Label)
        self.UCMPubCLI_username_label = QtWidgets.QLabel(self.widget_15)
        self.UCMPubCLI_username_label.setObjectName("UCMPubCLI_username_label")
        self.verticalLayout_18.addWidget(self.UCMPubCLI_username_label)
        self.label_22 = QtWidgets.QLabel(self.widget_15)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_18.addWidget(self.label_22)
        self.horizontalLayout_9.addWidget(self.widget_15)
        self.widget_19 = QtWidgets.QWidget(self.widget_24)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.UCMPub_IP_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        self.UCMPub_IP_CLI_line.setMinimumSize(QtCore.QSize(0, 17))
        self.UCMPub_IP_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_IP_CLI_line.setObjectName("UCMPub_IP_CLI_line")
        self.verticalLayout_19.addWidget(self.UCMPub_IP_CLI_line)
        self.UCMPub_Username_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        self.UCMPub_Username_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Username_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Username_CLI_line.setObjectName("UCMPub_Username_CLI_line")
        self.verticalLayout_19.addWidget(self.UCMPub_Username_CLI_line)
        self.UCMPub_Password_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        self.UCMPub_Password_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Password_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Password_CLI_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UCMPub_Password_CLI_line.setObjectName("UCMPub_Password_CLI_line")
        self.verticalLayout_19.addWidget(self.UCMPub_Password_CLI_line)
        self.horizontalLayout_9.addWidget(self.widget_19)
        self.UCMPub_Label.raise_()
        self.widget_19.raise_()
        self.label_22.raise_()
        self.widget_15.raise_()
        self.horizontalLayout_11.addWidget(self.widget_24)
        self.widget_22 = QtWidgets.QWidget(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_21 = QtWidgets.QWidget(self.widget_22)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 38))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_product_vos_gen = QtWidgets.QLabel(self.widget_21)
        self.label_product_vos_gen.setObjectName("label_product_vos_gen")
        self.horizontalLayout_10.addWidget(self.label_product_vos_gen)
        self.comboBox_product_vos_gen = QtWidgets.QComboBox(self.widget_21)
        self.comboBox_product_vos_gen.setObjectName("comboBox_product_vos_gen")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_product_vos_gen)
        self.verticalLayout_22.addWidget(self.widget_21)
        self.widget_26 = QtWidgets.QWidget(self.widget_22)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_vos_sub = QtWidgets.QRadioButton(self.widget_26)
        self.radioButton_vos_sub.setObjectName("radioButton_vos_sub")
        self.horizontalLayout_2.addWidget(self.radioButton_vos_sub)
        self.radioButton_vos_pub = QtWidgets.QRadioButton(self.widget_26)
        self.radioButton_vos_pub.setObjectName("radioButton_vos_pub")
        self.horizontalLayout_2.addWidget(self.radioButton_vos_pub)
        self.verticalLayout_22.addWidget(self.widget_26)
        self.widget_45 = QtWidgets.QWidget(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_45.sizePolicy().hasHeightForWidth())
        self.widget_45.setSizePolicy(sizePolicy)
        self.widget_45.setMinimumSize(QtCore.QSize(0, 51))
        self.widget_45.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_45.setObjectName("widget_45")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_45)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_discover_nodes_UCM = QtWidgets.QPushButton(self.widget_45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_discover_nodes_UCM.sizePolicy().hasHeightForWidth())
        self.pushButton_discover_nodes_UCM.setSizePolicy(sizePolicy)
        self.pushButton_discover_nodes_UCM.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_discover_nodes_UCM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_discover_nodes_UCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_discover_nodes_UCM.setAutoFillBackground(True)
        self.pushButton_discover_nodes_UCM.setObjectName("pushButton_discover_nodes_UCM")
        self.horizontalLayout_13.addWidget(self.pushButton_discover_nodes_UCM)
        self.verticalLayout_22.addWidget(self.widget_45)
        self.widget_23 = QtWidgets.QWidget(self.widget_22)
        self.widget_23.setMinimumSize(QtCore.QSize(0, 38))
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_add_node = QtWidgets.QPushButton(self.widget_23)
        self.pushButton_add_node.setObjectName("pushButton_add_node")
        self.horizontalLayout_5.addWidget(self.pushButton_add_node)
        self.verticalLayout_22.addWidget(self.widget_23)
        self.horizontalLayout_11.addWidget(self.widget_22)
        self.verticalLayout_21.addWidget(self.widget_25)
        self.widget_46 = QtWidgets.QWidget(self.widget_30)
        self.widget_46.setMinimumSize(QtCore.QSize(621, 0))
        self.widget_46.setObjectName("widget_46")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_46)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tableWidget_ucm_cluster_cli = QtWidgets.QTableWidget(self.widget_46)
        self.tableWidget_ucm_cluster_cli.setAlternatingRowColors(True)
        self.tableWidget_ucm_cluster_cli.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ucm_cluster_cli.setShowGrid(False)
        self.tableWidget_ucm_cluster_cli.setColumnCount(6)
        self.tableWidget_ucm_cluster_cli.setObjectName("tableWidget_ucm_cluster_cli")
        self.tableWidget_ucm_cluster_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(5, item)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_17.addWidget(self.tableWidget_ucm_cluster_cli)
        self.verticalLayout_21.addWidget(self.widget_46)
        self.widget_46.raise_()
        self.UCMPub_Label.raise_()
        self.widget_25.raise_()
        self.horizontalLayout_30.addWidget(self.widget_30)
        self.widget_47 = QtWidgets.QWidget(self.page_VOS)
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_47)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_49 = QtWidgets.QWidget(self.widget_47)
        self.widget_49.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_49.setObjectName("widget_49")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_49)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.treeWidget_ucm_cli = QtWidgets.QTreeWidget(self.widget_49)
        self.treeWidget_ucm_cli.setToolTip("")
        self.treeWidget_ucm_cli.setStatusTip("")
        self.treeWidget_ucm_cli.setObjectName("treeWidget_ucm_cli")
        self.verticalLayout_20.addWidget(self.treeWidget_ucm_cli)
        self.verticalLayout_12.addWidget(self.widget_49)
        self.widget_50 = QtWidgets.QWidget(self.widget_47)
        self.widget_50.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_50.setObjectName("widget_50")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_50)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_vos_refresh = QtWidgets.QPushButton(self.widget_50)
        self.pushButton_vos_refresh.setObjectName("pushButton_vos_refresh")
        self.verticalLayout_14.addWidget(self.pushButton_vos_refresh)
        self.pushButton_execute_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_execute_cli_ucm.sizePolicy().hasHeightForWidth())
        self.pushButton_execute_cli_ucm.setSizePolicy(sizePolicy)
        self.pushButton_execute_cli_ucm.setObjectName("pushButton_execute_cli_ucm")
        self.verticalLayout_14.addWidget(self.pushButton_execute_cli_ucm)
        self.pushButton_stop_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        self.pushButton_stop_cli_ucm.setObjectName("pushButton_stop_cli_ucm")
        self.verticalLayout_14.addWidget(self.pushButton_stop_cli_ucm)
        self.verticalLayout_12.addWidget(self.widget_50)
        self.horizontalLayout_30.addWidget(self.widget_47)
        self.toolBox.addItem(self.page_VOS, "")
        self.horizontalLayout_12.addWidget(self.toolBox)
        self.globalwidget.addTab(self.tab_cli, "")
        self.horizontalLayout.addWidget(self.globalwidget)

        self.retranslateUi(Gnosis)
        self.globalwidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gnosis)

    def retranslateUi(self, Gnosis):
        _translate = QtCore.QCoreApplication.translate
        Gnosis.setWindowTitle(_translate("Gnosis", "Gnosis"))
        self.label_ip_address_sql.setText(_translate("Gnosis", "UCM publisher IP"))
        self.label_username_sql.setText(_translate("Gnosis", "AXL username    "))
        self.label_password_sql.setText(_translate("Gnosis", "AXL password     "))
        self.SQLquery.setPlainText(_translate("Gnosis", "select name, description from device where name like \'SEP%\'"))
        self.pushButton_sql_execute.setText(_translate("Gnosis", "Execute Query"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_SQL), _translate("Gnosis", "SQL"))
        self.UCMPub_Label.setText(_translate("Gnosis", "IP address"))
        self.UCMPubCLI_username_label.setText(_translate("Gnosis", "Platform username"))
        self.label_22.setText(_translate("Gnosis", "Platform password"))
        self.label_product_vos_gen.setText(_translate("Gnosis", "Product"))
        self.comboBox_product_vos_gen.setItemText(0, _translate("Gnosis", "UCM"))
        self.comboBox_product_vos_gen.setItemText(1, _translate("Gnosis", "IMP"))
        self.comboBox_product_vos_gen.setItemText(2, _translate("Gnosis", "CUC"))
        self.comboBox_product_vos_gen.setItemText(3, _translate("Gnosis", "CER"))
        self.radioButton_vos_sub.setText(_translate("Gnosis", "Subscriber"))
        self.radioButton_vos_pub.setText(_translate("Gnosis", "Publisher"))
        self.pushButton_discover_nodes_UCM.setText(_translate("Gnosis", "DISCOVER CLUSTER \n"
" <from ucm publisher>"))
        self.pushButton_add_node.setText(_translate("Gnosis", "ADD NODE"))
        self.tableWidget_ucm_cluster_cli.setSortingEnabled(True)
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(0)
        item.setText(_translate("Gnosis", "address"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(1)
        item.setText(_translate("Gnosis", "role"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(2)
        item.setText(_translate("Gnosis", "type"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(3)
        item.setText(_translate("Gnosis", "dbRole"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(4)
        item.setText(_translate("Gnosis", "hostname"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(5)
        item.setText(_translate("Gnosis", "status"))
        self.treeWidget_ucm_cli.headerItem().setText(0, _translate("Gnosis", "CLI Commands"))
        self.pushButton_vos_refresh.setText(_translate("Gnosis", "REFRESH"))
        self.pushButton_execute_cli_ucm.setText(_translate("Gnosis", "START"))
        self.pushButton_stop_cli_ucm.setText(_translate("Gnosis", "STOP"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_VOS), _translate("Gnosis", "VOS"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_cli), _translate("Gnosis", "Platform"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gnosis = QtWidgets.QDialog()
    ui = Ui_Gnosis()
    ui.setupUi(Gnosis)
    Gnosis.show()
    sys.exit(app.exec_())

