# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nautilus_v1.5_Beta6.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Nautilus(object):
    def setupUi(self, Nautilus):
        Nautilus.setObjectName("Nautilus")
        Nautilus.resize(1404, 694)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        Nautilus.setPalette(palette)
        Nautilus.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.gridLayout_2 = QtWidgets.QGridLayout(Nautilus)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.globalwidget = QtWidgets.QTabWidget(Nautilus)
        self.globalwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.globalwidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.globalwidget.setFont(font)
        self.globalwidget.setToolTip("")
        self.globalwidget.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.globalwidget.setObjectName("globalwidget")
        self.tab_SQL = QtWidgets.QWidget()
        self.tab_SQL.setObjectName("tab_SQL")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_SQL)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.tab_SQL)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(275, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ip_address_sql = QtWidgets.QLabel(self.widget_3)
        self.label_ip_address_sql.setObjectName("label_ip_address_sql")
        self.verticalLayout.addWidget(self.label_ip_address_sql)
        self.label_username_sql = QtWidgets.QLabel(self.widget_3)
        self.label_username_sql.setMinimumSize(QtCore.QSize(0, 0))
        self.label_username_sql.setObjectName("label_username_sql")
        self.verticalLayout.addWidget(self.label_username_sql)
        self.label_password_sql = QtWidgets.QLabel(self.widget_3)
        self.label_password_sql.setObjectName("label_password_sql")
        self.verticalLayout.addWidget(self.label_password_sql)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_ipaddress_sql = QtWidgets.QLineEdit(self.widget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_ipaddress_sql.setPalette(palette)
        self.lineEdit_ipaddress_sql.setText("")
        self.lineEdit_ipaddress_sql.setObjectName("lineEdit_ipaddress_sql")
        self.verticalLayout_2.addWidget(self.lineEdit_ipaddress_sql)
        self.lineEdit_username_sql = QtWidgets.QLineEdit(self.widget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_username_sql.setPalette(palette)
        self.lineEdit_username_sql.setText("")
        self.lineEdit_username_sql.setObjectName("lineEdit_username_sql")
        self.verticalLayout_2.addWidget(self.lineEdit_username_sql)
        self.lineEdit_password_sql = QtWidgets.QLineEdit(self.widget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_password_sql.setPalette(palette)
        self.lineEdit_password_sql.setText("")
        self.lineEdit_password_sql.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_sql.setObjectName("lineEdit_password_sql")
        self.verticalLayout_2.addWidget(self.lineEdit_password_sql)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.tab_SQL)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SQLquery = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLquery.sizePolicy().hasHeightForWidth())
        self.SQLquery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.SQLquery.setFont(font)
        self.SQLquery.setObjectName("SQLquery")
        self.horizontalLayout_4.addWidget(self.SQLquery)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_6)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SQLresponse = QtWidgets.QPlainTextEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLresponse.sizePolicy().hasHeightForWidth())
        self.SQLresponse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.SQLresponse.setFont(font)
        self.SQLresponse.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.SQLresponse.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SQLresponse.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.SQLresponse.setPlainText("")
        self.SQLresponse.setObjectName("SQLresponse")
        self.horizontalLayout_3.addWidget(self.SQLresponse)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_executeSql = QtWidgets.QWidget(self.tab_SQL)
        self.widget_executeSql.setObjectName("widget_executeSql")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_executeSql)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_sql_execute = QtWidgets.QPushButton(self.widget_executeSql)
        self.pushButton_sql_execute.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_sql_execute.setMaximumSize(QtCore.QSize(141, 16777215))
        self.pushButton_sql_execute.setObjectName("pushButton_sql_execute")
        self.horizontalLayout_6.addWidget(self.pushButton_sql_execute)
        self.verticalLayout_4.addWidget(self.widget_executeSql)
        self.globalwidget.addTab(self.tab_SQL, "")
        self.tab_cli = QtWidgets.QWidget()
        self.tab_cli.setObjectName("tab_cli")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_cli)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolBox = QtWidgets.QToolBox(self.tab_cli)
        self.toolBox.setObjectName("toolBox")
        self.page_VOS = QtWidgets.QWidget()
        self.page_VOS.setGeometry(QtCore.QRect(0, 0, 1362, 605))
        self.page_VOS.setObjectName("page_VOS")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.page_VOS)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.widget_30 = QtWidgets.QWidget(self.page_VOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_30.sizePolicy().hasHeightForWidth())
        self.widget_30.setSizePolicy(sizePolicy)
        self.widget_30.setMinimumSize(QtCore.QSize(660, 0))
        self.widget_30.setMaximumSize(QtCore.QSize(600, 169865))
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_25 = QtWidgets.QWidget(self.widget_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(230, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_24 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setMaximumSize(QtCore.QSize(16777215, 108))
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_15 = QtWidgets.QWidget(self.widget_24)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.UCMPub_Label = QtWidgets.QLabel(self.widget_15)
        self.UCMPub_Label.setObjectName("UCMPub_Label")
        self.verticalLayout_18.addWidget(self.UCMPub_Label)
        self.UCMPubCLI_username_label = QtWidgets.QLabel(self.widget_15)
        self.UCMPubCLI_username_label.setObjectName("UCMPubCLI_username_label")
        self.verticalLayout_18.addWidget(self.UCMPubCLI_username_label)
        self.label_22 = QtWidgets.QLabel(self.widget_15)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_18.addWidget(self.label_22)
        self.horizontalLayout.addWidget(self.widget_15)
        self.widget_19 = QtWidgets.QWidget(self.widget_24)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.UCMPub_IP_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UCMPub_IP_CLI_line.sizePolicy().hasHeightForWidth())
        self.UCMPub_IP_CLI_line.setSizePolicy(sizePolicy)
        self.UCMPub_IP_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_IP_CLI_line.setMaximumSize(QtCore.QSize(23, 16777215))
        self.UCMPub_IP_CLI_line.setText("")
        self.UCMPub_IP_CLI_line.setObjectName("UCMPub_IP_CLI_line")
        self.verticalLayout_6.addWidget(self.UCMPub_IP_CLI_line)
        self.UCMPub_Username_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        self.UCMPub_Username_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Username_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Username_CLI_line.setText("")
        self.UCMPub_Username_CLI_line.setObjectName("UCMPub_Username_CLI_line")
        self.verticalLayout_6.addWidget(self.UCMPub_Username_CLI_line)
        self.UCMPub_Password_CLI_line = QtWidgets.QLineEdit(self.widget_19)
        self.UCMPub_Password_CLI_line.setMinimumSize(QtCore.QSize(117, 17))
        self.UCMPub_Password_CLI_line.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Password_CLI_line.setText("")
        self.UCMPub_Password_CLI_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UCMPub_Password_CLI_line.setObjectName("UCMPub_Password_CLI_line")
        self.verticalLayout_6.addWidget(self.UCMPub_Password_CLI_line)
        self.horizontalLayout.addWidget(self.widget_19)
        self.widget_19.raise_()
        self.widget_15.raise_()
        self.verticalLayout_8.addWidget(self.widget_24)
        self.widget_10 = QtWidgets.QWidget(self.groupBox)
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_discover_nodes_UCM = QtWidgets.QPushButton(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_discover_nodes_UCM.sizePolicy().hasHeightForWidth())
        self.pushButton_discover_nodes_UCM.setSizePolicy(sizePolicy)
        self.pushButton_discover_nodes_UCM.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_discover_nodes_UCM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_discover_nodes_UCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_discover_nodes_UCM.setAutoFillBackground(True)
        self.pushButton_discover_nodes_UCM.setObjectName("pushButton_discover_nodes_UCM")
        self.verticalLayout_15.addWidget(self.pushButton_discover_nodes_UCM)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_25)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_16 = QtWidgets.QWidget(self.widget_9)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.UCMPub_Label_2 = QtWidgets.QLabel(self.widget_16)
        self.UCMPub_Label_2.setObjectName("UCMPub_Label_2")
        self.verticalLayout_19.addWidget(self.UCMPub_Label_2)
        self.UCMPubCLI_username_label_2 = QtWidgets.QLabel(self.widget_16)
        self.UCMPubCLI_username_label_2.setObjectName("UCMPubCLI_username_label_2")
        self.verticalLayout_19.addWidget(self.UCMPubCLI_username_label_2)
        self.label_23 = QtWidgets.QLabel(self.widget_16)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.horizontalLayout_9.addWidget(self.widget_16)
        self.widget_20 = QtWidgets.QWidget(self.widget_9)
        self.widget_20.setMinimumSize(QtCore.QSize(130, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.widget_20.setPalette(palette)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.UCMPub_IP_CLI_line_2 = QtWidgets.QLineEdit(self.widget_20)
        self.UCMPub_IP_CLI_line_2.setMinimumSize(QtCore.QSize(110, 17))
        self.UCMPub_IP_CLI_line_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_IP_CLI_line_2.setText("")
        self.UCMPub_IP_CLI_line_2.setObjectName("UCMPub_IP_CLI_line_2")
        self.verticalLayout_7.addWidget(self.UCMPub_IP_CLI_line_2)
        self.UCMPub_Username_CLI_line_2 = QtWidgets.QLineEdit(self.widget_20)
        self.UCMPub_Username_CLI_line_2.setMinimumSize(QtCore.QSize(110, 17))
        self.UCMPub_Username_CLI_line_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Username_CLI_line_2.setText("")
        self.UCMPub_Username_CLI_line_2.setObjectName("UCMPub_Username_CLI_line_2")
        self.verticalLayout_7.addWidget(self.UCMPub_Username_CLI_line_2)
        self.UCMPub_Password_CLI_line_2 = QtWidgets.QLineEdit(self.widget_20)
        self.UCMPub_Password_CLI_line_2.setMinimumSize(QtCore.QSize(110, 17))
        self.UCMPub_Password_CLI_line_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.UCMPub_Password_CLI_line_2.setText("")
        self.UCMPub_Password_CLI_line_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UCMPub_Password_CLI_line_2.setObjectName("UCMPub_Password_CLI_line_2")
        self.verticalLayout_7.addWidget(self.UCMPub_Password_CLI_line_2)
        self.horizontalLayout_9.addWidget(self.widget_20)
        self.widget_8 = QtWidgets.QWidget(self.widget_9)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_26 = QtWidgets.QWidget(self.widget_8)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_vos_sub = QtWidgets.QRadioButton(self.widget_26)
        self.radioButton_vos_sub.setChecked(True)
        self.radioButton_vos_sub.setObjectName("radioButton_vos_sub")
        self.horizontalLayout_2.addWidget(self.radioButton_vos_sub)
        self.radioButton_vos_pub = QtWidgets.QRadioButton(self.widget_26)
        self.radioButton_vos_pub.setChecked(False)
        self.radioButton_vos_pub.setObjectName("radioButton_vos_pub")
        self.horizontalLayout_2.addWidget(self.radioButton_vos_pub)
        self.verticalLayout_14.addWidget(self.widget_26)
        self.widget_21 = QtWidgets.QWidget(self.widget_8)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 38))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_product_vos_gen = QtWidgets.QLabel(self.widget_21)
        self.label_product_vos_gen.setObjectName("label_product_vos_gen")
        self.horizontalLayout_10.addWidget(self.label_product_vos_gen)
        self.comboBox_product_vos_gen = QtWidgets.QComboBox(self.widget_21)
        self.comboBox_product_vos_gen.setObjectName("comboBox_product_vos_gen")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.comboBox_product_vos_gen.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_product_vos_gen)
        self.verticalLayout_14.addWidget(self.widget_21)
        self.widget_21.raise_()
        self.widget_26.raise_()
        self.horizontalLayout_9.addWidget(self.widget_8)
        self.verticalLayout_13.addWidget(self.widget_9)
        self.widget_27 = QtWidgets.QWidget(self.widget_7)
        self.widget_27.setMinimumSize(QtCore.QSize(0, 38))
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_add_node = QtWidgets.QPushButton(self.widget_27)
        self.pushButton_add_node.setObjectName("pushButton_add_node")
        self.horizontalLayout_11.addWidget(self.pushButton_add_node)
        self.verticalLayout_13.addWidget(self.widget_27)
        self.verticalLayout_9.addWidget(self.widget_7)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout_10.addWidget(self.widget_25)
        self.widget_46 = QtWidgets.QWidget(self.widget_30)
        self.widget_46.setMinimumSize(QtCore.QSize(621, 0))
        self.widget_46.setObjectName("widget_46")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_46)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tableWidget_ucm_cluster_cli = QtWidgets.QTableWidget(self.widget_46)
        self.tableWidget_ucm_cluster_cli.setAlternatingRowColors(False)
        self.tableWidget_ucm_cluster_cli.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ucm_cluster_cli.setShowGrid(False)
        self.tableWidget_ucm_cluster_cli.setColumnCount(5)
        self.tableWidget_ucm_cluster_cli.setObjectName("tableWidget_ucm_cluster_cli")
        self.tableWidget_ucm_cluster_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ucm_cluster_cli.setHorizontalHeaderItem(4, item)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setHighlightSections(True)
        self.tableWidget_ucm_cluster_cli.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ucm_cluster_cli.verticalHeader().setHighlightSections(True)
        self.verticalLayout_17.addWidget(self.tableWidget_ucm_cluster_cli)
        self.verticalLayout_10.addWidget(self.widget_46)
        self.widget_46.raise_()
        self.widget_25.raise_()
        self.horizontalLayout_30.addWidget(self.widget_30)
        self.widget_47 = QtWidgets.QWidget(self.page_VOS)
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_47)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_49 = QtWidgets.QWidget(self.widget_47)
        self.widget_49.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_49.setObjectName("widget_49")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_49)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_50 = QtWidgets.QWidget(self.widget_49)
        self.widget_50.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_50.setObjectName("widget_50")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_execute_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_execute_cli_ucm.sizePolicy().hasHeightForWidth())
        self.pushButton_execute_cli_ucm.setSizePolicy(sizePolicy)
        self.pushButton_execute_cli_ucm.setObjectName("pushButton_execute_cli_ucm")
        self.horizontalLayout_5.addWidget(self.pushButton_execute_cli_ucm)
        self.pushButton_stop_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        self.pushButton_stop_cli_ucm.setObjectName("pushButton_stop_cli_ucm")
        self.horizontalLayout_5.addWidget(self.pushButton_stop_cli_ucm)
        self.pushButton_refresh_cli_ucm = QtWidgets.QPushButton(self.widget_50)
        self.pushButton_refresh_cli_ucm.setObjectName("pushButton_refresh_cli_ucm")
        self.horizontalLayout_5.addWidget(self.pushButton_refresh_cli_ucm)
        self.verticalLayout_20.addWidget(self.widget_50)
        self.treeWidget_ucm_cli = QtWidgets.QTreeWidget(self.widget_49)
        self.treeWidget_ucm_cli.setToolTip("")
        self.treeWidget_ucm_cli.setStatusTip("")
        self.treeWidget_ucm_cli.setAutoExpandDelay(0)
        self.treeWidget_ucm_cli.setObjectName("treeWidget_ucm_cli")
        self.verticalLayout_20.addWidget(self.treeWidget_ucm_cli)
        self.verticalLayout_12.addWidget(self.widget_49)
        self.horizontalLayout_30.addWidget(self.widget_47)
        self.toolBox.addItem(self.page_VOS, "")
        self.horizontalLayout_12.addWidget(self.toolBox)
        self.globalwidget.addTab(self.tab_cli, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_38 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_38.sizePolicy().hasHeightForWidth())
        self.widget_38.setSizePolicy(sizePolicy)
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_11 = QtWidgets.QWidget(self.widget_38)
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.groupBox_21 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_21.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_8 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_27.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_username_tp = QtWidgets.QLabel(self.groupBox_21)
        self.label_username_tp.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_username_tp.setFont(font)
        self.label_username_tp.setObjectName("label_username_tp")
        self.horizontalLayout_19.addWidget(self.label_username_tp)
        self.lineEdit_username_tp = QtWidgets.QLineEdit(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_username_tp.sizePolicy().hasHeightForWidth())
        self.lineEdit_username_tp.setSizePolicy(sizePolicy)
        self.lineEdit_username_tp.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_username_tp.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lineEdit_username_tp.setPalette(palette)
        self.lineEdit_username_tp.setText("")
        self.lineEdit_username_tp.setObjectName("lineEdit_username_tp")
        self.horizontalLayout_19.addWidget(self.lineEdit_username_tp)
        self.verticalLayout_27.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_password_tp = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_password_tp.setFont(font)
        self.label_password_tp.setObjectName("label_password_tp")
        self.horizontalLayout_20.addWidget(self.label_password_tp)
        self.lineEdit_password_tp = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_password_tp.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_password_tp.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_password_tp.setPalette(palette)
        self.lineEdit_password_tp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_tp.setObjectName("lineEdit_password_tp")
        self.horizontalLayout_20.addWidget(self.lineEdit_password_tp)
        self.verticalLayout_27.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.label_concurrent_tp = QtWidgets.QLabel(self.groupBox_21)
        self.label_concurrent_tp.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_concurrent_tp.setFont(font)
        self.label_concurrent_tp.setObjectName("label_concurrent_tp")
        self.horizontalLayout_14.addWidget(self.label_concurrent_tp)
        self.lineEdit_concurrent_tp = QtWidgets.QLineEdit(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_concurrent_tp.sizePolicy().hasHeightForWidth())
        self.lineEdit_concurrent_tp.setSizePolicy(sizePolicy)
        self.lineEdit_concurrent_tp.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_concurrent_tp.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_concurrent_tp.setPalette(palette)
        self.lineEdit_concurrent_tp.setObjectName("lineEdit_concurrent_tp")
        self.horizontalLayout_14.addWidget(self.lineEdit_concurrent_tp)
        self.verticalLayout_27.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_22.addWidget(self.groupBox_21)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_28.addWidget(self.label_9)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setOpenExternalLinks(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.lineEdit_webex_token = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_webex_token.sizePolicy().hasHeightForWidth())
        self.lineEdit_webex_token.setSizePolicy(sizePolicy)
        self.lineEdit_webex_token.setMaximumSize(QtCore.QSize(16777215, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_webex_token.setPalette(palette)
        self.lineEdit_webex_token.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_webex_token.setObjectName("lineEdit_webex_token")
        self.horizontalLayout_17.addWidget(self.lineEdit_webex_token)
        self.verticalLayout_28.addLayout(self.horizontalLayout_17)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setOpenExternalLinks(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_29.addWidget(self.label_11)
        self.verticalLayout_28.addLayout(self.verticalLayout_29)
        self.horizontalLayout_22.addWidget(self.groupBox_3)
        self.verticalLayout_30.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_38)
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_12.setObjectName("widget_12")
        self.formLayout = QtWidgets.QFormLayout(self.widget_12)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_run_TP_commands = QtWidgets.QPushButton(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run_TP_commands.sizePolicy().hasHeightForWidth())
        self.pushButton_run_TP_commands.setSizePolicy(sizePolicy)
        self.pushButton_run_TP_commands.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_run_TP_commands.setMaximumSize(QtCore.QSize(141, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_run_TP_commands.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_run_TP_commands.setFont(font)
        self.pushButton_run_TP_commands.setObjectName("pushButton_run_TP_commands")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_run_TP_commands)
        self.verticalLayout_30.addWidget(self.widget_12)
        self.groupBox_41 = QtWidgets.QGroupBox(self.widget_38)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_41.sizePolicy().hasHeightForWidth())
        self.groupBox_41.setSizePolicy(sizePolicy)
        self.groupBox_41.setObjectName("groupBox_41")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.groupBox_41)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.splitter = QtWidgets.QSplitter(self.groupBox_41)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.plainTextEdit_tp_data = QtWidgets.QPlainTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_tp_data.setFont(font)
        self.plainTextEdit_tp_data.setObjectName("plainTextEdit_tp_data")
        self.verticalLayout_11.addWidget(self.plainTextEdit_tp_data)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.plainTextEdit_tp_commands = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_tp_commands.setFont(font)
        self.plainTextEdit_tp_commands.setPlainText("")
        self.plainTextEdit_tp_commands.setObjectName("plainTextEdit_tp_commands")
        self.verticalLayout_16.addWidget(self.plainTextEdit_tp_commands)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_23.addWidget(self.label_4)
        self.plainTextEdit_TP_output = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_TP_output.setFont(font)
        self.plainTextEdit_TP_output.setObjectName("plainTextEdit_TP_output")
        self.verticalLayout_23.addWidget(self.plainTextEdit_TP_output)
        self.horizontalLayout_28.addWidget(self.splitter)
        self.verticalLayout_30.addWidget(self.groupBox_41)
        self.horizontalLayout_16.addWidget(self.widget_38)
        self.globalwidget.addTab(self.tab, "")
        self.tab_cms = QtWidgets.QWidget()
        self.tab_cms.setObjectName("tab_cms")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_cms)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_22 = QtWidgets.QWidget(self.tab_cms)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.widget_22)
        self.frame.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_28 = QtWidgets.QWidget(self.frame)
        self.widget_28.setMaximumSize(QtCore.QSize(80, 80))
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_username_tp_2 = QtWidgets.QLabel(self.widget_28)
        self.label_username_tp_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_username_tp_2.setFont(font)
        self.label_username_tp_2.setObjectName("label_username_tp_2")
        self.verticalLayout_21.addWidget(self.label_username_tp_2)
        self.label_password_tp_2 = QtWidgets.QLabel(self.widget_28)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_password_tp_2.setFont(font)
        self.label_password_tp_2.setObjectName("label_password_tp_2")
        self.verticalLayout_21.addWidget(self.label_password_tp_2)
        self.horizontalLayout_15.addWidget(self.widget_28)
        self.widget_29 = QtWidgets.QWidget(self.frame)
        self.widget_29.setMaximumSize(QtCore.QSize(150, 80))
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lineEdit_username_tp_2 = QtWidgets.QLineEdit(self.widget_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_username_tp_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_username_tp_2.setSizePolicy(sizePolicy)
        self.lineEdit_username_tp_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.lineEdit_username_tp_2.setObjectName("lineEdit_username_tp_2")
        self.verticalLayout_22.addWidget(self.lineEdit_username_tp_2)
        self.lineEdit_password_tp_2 = QtWidgets.QLineEdit(self.widget_29)
        self.lineEdit_password_tp_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.lineEdit_password_tp_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_tp_2.setObjectName("lineEdit_password_tp_2")
        self.verticalLayout_22.addWidget(self.lineEdit_password_tp_2)
        self.horizontalLayout_15.addWidget(self.widget_29)
        self.horizontalLayout_13.addWidget(self.frame)
        self.widget_23 = QtWidgets.QWidget(self.widget_22)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_13.addWidget(self.widget_23)
        self.verticalLayout_5.addWidget(self.widget_22)
        self.widget_17 = QtWidgets.QWidget(self.tab_cms)
        self.widget_17.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_17.setObjectName("widget_17")
        self.pushButton = QtWidgets.QPushButton(self.widget_17)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.tab_cms)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_5.addWidget(self.widget_18)
        self.globalwidget.addTab(self.tab_cms, "")
        self.gridLayout_2.addWidget(self.globalwidget, 0, 0, 1, 1)

        self.retranslateUi(Nautilus)
        self.globalwidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Nautilus)

    def retranslateUi(self, Nautilus):
        _translate = QtCore.QCoreApplication.translate
        Nautilus.setWindowTitle(_translate("Nautilus", "Nautilus 1.5 Beta 6"))
        self.label_ip_address_sql.setText(_translate("Nautilus", "UCM publisher IP"))
        self.label_username_sql.setText(_translate("Nautilus", "AXL username    "))
        self.label_password_sql.setText(_translate("Nautilus", "AXL password     "))
        self.SQLquery.setPlainText(_translate("Nautilus", "select name, description from device where name like \'SEP%\'"))
        self.pushButton_sql_execute.setText(_translate("Nautilus", "Execute Query"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_SQL), _translate("Nautilus", "SQL"))
        self.UCMPub_Label.setText(_translate("Nautilus", "UCM Pub"))
        self.UCMPubCLI_username_label.setText(_translate("Nautilus", "OS user"))
        self.label_22.setText(_translate("Nautilus", "OS pass"))
        self.pushButton_discover_nodes_UCM.setText(_translate("Nautilus", "DISCOVER CLUSTER"))
        self.UCMPub_Label_2.setText(_translate("Nautilus", "IP addr"))
        self.UCMPubCLI_username_label_2.setText(_translate("Nautilus", "OS  user"))
        self.label_23.setText(_translate("Nautilus", "OS pass"))
        self.radioButton_vos_sub.setText(_translate("Nautilus", "Sub"))
        self.radioButton_vos_pub.setText(_translate("Nautilus", "Pub"))
        self.label_product_vos_gen.setText(_translate("Nautilus", "Product"))
        self.comboBox_product_vos_gen.setItemText(0, _translate("Nautilus", "UCM"))
        self.comboBox_product_vos_gen.setItemText(1, _translate("Nautilus", "IMP"))
        self.comboBox_product_vos_gen.setItemText(2, _translate("Nautilus", "CUC"))
        self.comboBox_product_vos_gen.setItemText(3, _translate("Nautilus", "CER"))
        self.pushButton_add_node.setText(_translate("Nautilus", "ADD NODE"))
        self.tableWidget_ucm_cluster_cli.setSortingEnabled(True)
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(0)
        item.setText(_translate("Nautilus", "address"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(1)
        item.setText(_translate("Nautilus", "product"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(2)
        item.setText(_translate("Nautilus", "role"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(3)
        item.setText(_translate("Nautilus", "username"))
        item = self.tableWidget_ucm_cluster_cli.horizontalHeaderItem(4)
        item.setText(_translate("Nautilus", "password"))
        self.pushButton_execute_cli_ucm.setText(_translate("Nautilus", "START"))
        self.pushButton_stop_cli_ucm.setText(_translate("Nautilus", "STOP"))
        self.pushButton_refresh_cli_ucm.setText(_translate("Nautilus", "REFRESH"))
        self.treeWidget_ucm_cli.headerItem().setText(0, _translate("Nautilus", "CLI Commands"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_VOS), _translate("Nautilus", "VOS"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_cli), _translate("Nautilus", "Platform"))
        self.label_8.setText(_translate("Nautilus", "onPrem Telepresence credentials"))
        self.label_username_tp.setText(_translate("Nautilus", "TP username"))
        self.label_password_tp.setText(_translate("Nautilus", "TP password"))
        self.label_concurrent_tp.setText(_translate("Nautilus", "Concurrency"))
        self.lineEdit_concurrent_tp.setText(_translate("Nautilus", "20"))
        self.label_9.setText(_translate("Nautilus", "Webex Authentication"))
        self.label_10.setText(_translate("Nautilus", "<html><head/><body><p><a href=\"http://localhost:10060/\"><span style=\" text-decoration: underline; color:#0000ff;\">Webex login</span></a></p></body></html>"))
        self.label_12.setText(_translate("Nautilus", "       OR ENTER ACCESS TOKEN MANUALLY      "))
        self.label_11.setText(_translate("Nautilus", "<html><head/><body><p><a href=\"https://github.com/isidrov/Nautilus\"><span style=\" text-decoration: underline; color:#0000ff;\">Readme</span></a></p></body></html>"))
        self.pushButton_run_TP_commands.setText(_translate("Nautilus", "Run"))
        self.label.setText(_translate("Nautilus", "Data"))
        self.label_2.setText(_translate("Nautilus", "Commands"))
        self.label_4.setText(_translate("Nautilus", "JSON Output"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab), _translate("Nautilus", "Video / Webex"))
        self.label_username_tp_2.setText(_translate("Nautilus", "  username    "))
        self.label_password_tp_2.setText(_translate("Nautilus", "  password     "))
        self.pushButton.setText(_translate("Nautilus", "Run"))
        self.globalwidget.setTabText(self.globalwidget.indexOf(self.tab_cms), _translate("Nautilus", "Cisco Meeting Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Nautilus = QtWidgets.QDialog()
    ui = Ui_Nautilus()
    ui.setupUi(Nautilus)
    Nautilus.show()
    sys.exit(app.exec_())

